
<head>
    <style>
        body {
            background: #ffffff url("/foto/wood.jpg") ;
        }
        #Wrapper
        {
            width: 300px;
            height: 160px;
            position: absolute;
            left: 50%;
            top: 50%;
            margin:-80px 0 0 -150px;
        }
    </style>
</head>
<body>
<div id="Wrapper">
    <form class="form-signin" role="form" action="/giris/kontrol" method="post">
        <font color="white"><h2 class="form-signin-heading">SİSTEME GİRİŞ</h2></font>
        <input type="text" class="form-control" placeholder="Kullanıcı Adı" required autofocus name="kullanici_adi">
        <input type="password" class="form-control" placeholder="Şifre" required name="parola">
        <br>
        <button class="btn btn-lg btn-success btn-block" type="submit">Giriş Yap</button>
    </form>
</div>
</body>
