<table class="table table-bordered table-stripped" >
	<thead>
		<th>Sıra</th>
		<th>Fotoğraf</th>
		<th>Adı</th>
		<th>Soyadı</th>
		<th>Not</th>
		<th>Harf Notu</th>
	</thead>
	<tbody>
		<?php foreach($this->data as $i=> $satir):?>
    <tr>
        <td><a href="/not/duzenle/id/<?php echo $satir['id']?>"><?php echo $i+1?></td>
        <td><img src="/foto/<?php echo $satir['fotograf']?>" height="50" width="50" /></td>
        <td><?php echo $satir['adi']?></a></td>
        <td><?php echo $satir['soyadi']?></td>
        <td><?php echo $satir['notu']?></td>
        <td><?php echo $satir['harf_notu']?></td>
    </tr>
<?php endforeach?>
</tbody>
</table>
<input type="text" name="adi" value="<?php echo $this->data['adi'] ?>">