<h3> SİSTEME GİRİŞ </h3>
<form method="post" action="/erhangiris/kontrol">
<table>
<tr>
	<td>Kullanıcı Adı</td>
	<td><input type="text" name="kullanici_adi"></td>
</tr>
<tr>
	<td>Şifre</td>
	<td><input type="password" name="parola"></td>
</tr>
</table>
<button type="submit" class="btn btn-success btn-sm">GİRİŞ YAP</button>
<a href="/erhangiris/kayit" class="btn btn-info btn-sm">KAYIT OL</a>
</form>