<form method="post" action="/erhangiris/kayitt">
<table>
<tr>
	<td>Adı</td>
	<td><input type="text" name="adi"></td>
</tr>
<tr>
	<td>Soyadı</td>
	<td><input type="text" name="soyadi"></td>
</tr>
<tr>
	<td>Kullanıcı Adı</td>
	<td><input type="text" name="kullanici_adi"></td>
</tr>
<tr>
	<td>Durum</td>
	<td><input type="text" name="durum"></td>
</tr>
<tr>
	<td>Şifre</td>
	<td><input type="password" name="parola"></td>
	<td>Şifre Tekrar</td>
	<td><input type="password" name="tparola"></td>
</tr>
</table>
<button type="submit" class="btn btn-success btn-sm">KAYIT OL</button>
</form>