<?php if ($this->pageCount) :
    $midRange = floor(sizeof($this->pagesInRange) / 2);
    if (($this->current + $midRange) < $this->pageCount) :
        array_pop($this->pagesInRange);
        $display_end = true;
    endif; ?>
    <div class="paginationControl<?= $this->position; ?>">
        <div class="paginationControl_showing">
            Viewing page <strong class="current"><?= $this->current; ?></strong> of <strong class="last"><?= $this->last; ?></strong>
        </div>
        <div class="paginationControl_pages">
            <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
             <li><a href="javascript:void(0)" onclick="ara(<?php echo $this->previous ?>)" class="previous" >&lt; Previous</a></li>
            <?php else: ?>
               <li><span class="disabled">&lt; Previous</span> |</li>
            <?php endif; ?>
            <?php if (($this->current - $midRange) > $this->first): ?>
                <?php array_shift($this->pagesInRange);?>
             <li><a href="javascript:void(0)" onclick="ara(<?php echo $this->first ?>)" ><?php echo $this->first ?></a></li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>

                <?php if ($page != $this->current): ?>
                    <li><a href="javascript:void(0)" onclick="ara(<?php echo $page; ?>)" ><?php echo $page; ?></a></li>
                <?php else: ?>
                   <li><strong><?php echo $page; ?></strong></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if (!empty($display_end)) : ?>
               <li><a href="javascript:void(0)" onclick="ara(<?php echo $this->last; ?>)" ><?php echo $this->last ?></a></li>
            <?php endif; ?>
            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li><a href="javascript:void(0)" onclick="ara(<?php echo $this->next; ?>)" class="next">Next &gt;</a></li>
            <?php else: ?>
                <li><span class="disabled">Next &gt;</span></li>
            <?php endif; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>