<html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo $this->baslik ?></title>
        <link href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="stylesheet" />
        <link rel="stylesheet" href="../../../css/bootstrap.css"><!-- bootstrapin kaynak stil dosyalarının yolunu belirt -->
        <link rel="stylesheet" href="../../../css/bootstrap-theme.min.css"><!-- bootstrap opsiyonel temaların yolunu belirt -->

        <script src=" http://code.jquery.com/jquery-2.1.1.min.js"></script><!--jquery dosyasının indirileceği yolu belirt-->
                <script src="../../../js/bootstrap.min.js"></script><!-- bootstrap in script dosyalarının indirileceği yolu belirt-->
    
    <script language="Javascript">
    $(function(){
        window.setTimeout(mesajlariTemizle,2000);
    });
    
    function mesajlariTemizle(){
        $("#hataMesaji").hide("slow");
        $("#bilgiMesaji").hide("slow");
    }


    </script>

    </head>
    <body>
        <div class="bs-example">
            <nav class="navbar navbar-inverse" role="navigation">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-9">
                            <span class="sr-only"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/index/index">ESIS</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </div>

        <div class="container">

            <div style="clear:both" ></div> 
            <div style="float:left">
                <?php echo $this->layout()->content ?>
            </div>
            
            
            <p class="bg-success" id="bilgiMesaji"><?php echo $this->bilgiMesaji ?></p>
            <p class="bg-danger" id="hataMesaji"><?php echo $this->hataMesaji ?></p>


                <a href="/giris/logout" class="btn btn-danger btn-sm pull-right">Çıkış Yap</a>

            
            <div style="clear:both"></div>
            <center>
                <div class="alert alert-info navbar-fixed-bottom"><a href="https://twitter.com/kelevl2a" style="color: midnightblue">Erhan Gülas</a></div>
            </center>
        </div>
    </body>
</html>