<h3> ADMİN GİRİŞ </h3>
    <table>
        <td>
            <a href="/admin/ders" class="btn btn-success btn-sm">DERS BİLGİLERİ</a>
        </td>
        <td>
            <a href="/admin/ogretmenbilgi" class="btn btn-warning btn-sm">ÖĞRETMEN BİLGİLERİ</a>
        </td>
        <td>
            <a href="/admin/ogrencibilgi" class="btn btn-info btn-sm">ÖĞRENCİ BİLGİLERİ</a>
        </td>

    </table>

<ul>
<?php foreach($this->menu as $menu): ?>
    <li><a href="/<?php echo $menu['controller'] ?>/<?php echo $menu['action'] ?>/" ><?php echo $menu['menu_adi'] ?></a></li>
<?php endforeach ?>
</ul>